name: Deploy to staging

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches: [staging]

jobs:
  deploy:
    runs-on: bpstaging-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch .env file from server
        run: |
          sshpass -p ${{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/staging-deployment/hng_boilerplate_expressjs/.env .env
        env:
          SSH_HOST: ${{ secrets.HOST }}
          SSH_USERNAME: ${{ secrets.USERNAME }}
          SSH_PASSWORD: ${{ secrets.PASSWORD }}

      - name: Pull from GitHub
        id: pull
        run: |
          remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          # git remote add action $remote_repo
          git clone $remote_repo staging

      - name: Sync with the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "staging/*"
          target: "~/staging-deployment/hng_boilerplate_expressjs/"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/staging-deployment/hng_boilerplate_expressjs
            git stash
            git checkout staging
            git pull
            npm install
            pm2 restart all
