name: Build, Test, and Deploy for Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/aihomework/staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Pull from GitHub
        run: |
          if [ ! -d ".git" ]; then
            echo "Cloning the repository..."
            git clone https://github.com/hngprojects/hng_boilerplate_expressjs.git
          fi
          git stash
          git pull origin staging

      - name: Install dependencies
        run: yarn install

      - name: Run Test
        run: yarn test

      - name: Build the dist
        run: yarn build

      - name: Migrate
        run: yarn reset-db

      - name: Setup service file
        run: sudo cp server-script/aihomeworkstaging.service /etc/systemd/system

      - name: Start the app
        run: |
          sudo systemctl daemon-reload
          sudo systemctl restart aihomeworkstaging
